name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ] # Se activa al intentar fusionar una rama

jobs:
  test:
    runs-on: ubuntu-latest # Sistema Operativo del servidor

    steps:
      - uses: actions/checkout@v3 # 1. GitHub clona tu repo

      - name: Set up JDK 25
        uses: actions/setup-java@v3 # 2. Instala Java 17
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Run JUnit tests
        run: mvn --batch-mode test # 3. Lanza los tests